PS4/PS4/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PS4.Models;

namespace PS4
{
    public class CreateModel : MyPageModel
    {
        [BindProperty]
        public Product newProduct { get; set; }
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid) return Page();
            LoadDB();
            productDB.Create(newProduct);
            SaveDB();
            return RedirectToPage("List");
        }
    }
}

PS4/PS4/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PS4.Models;

namespace PS4
{
    public class DeleteModel : MyPageModel
    {
        public IActionResult OnGet(int id)
        {
            LoadDB();
            productDB.Delete(id);
            SaveDB();
            return RedirectToPage("List");
        }
    }
}

PS4/PS4/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PS4.Models;
using PS4.DAL;
using Microsoft.AspNetCore.Http;

namespace PS4.Pages
{
    public class DetailsModel : MyPageModel
    {
        [BindProperty]
        public Product product { get; set; }

        public void OnGet(int id)
        {
            LoadDB();
            shopcartDB.Clear();
            for (int i = 1; ; i++)
            {
                string add = Request.Cookies[i.ToString()];
                if (add == null) break;
                else shopcartDB.AddToCart(productDB.lookforID(int.Parse(add)));
            }
            product = productDB.lookforID(id);
            SaveDB();
        }
        public IActionResult OnPostAdd(int id)
        {
            LoadDB();
            Product p = productDB.lookforID(id);

            var cookieOptions = new CookieOptions { Expires = DateTime.Now.AddDays(30) };

            shopcartDB.AddToCart(p);

            Response.Cookies.Append(shopcartDB.GetProductsList.Count.ToString(), p.id.ToString(), cookieOptions);

            SaveDB();
            return RedirectToPage("List");
        }
    }
}

PS4/PS4/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PS4.Models;
using PS4.DAL;

namespace PS4.Pages
{
    public class EditModel : MyPageModel
    {
        [BindProperty]
        public Product editProduct { get; set; }
        public void OnGet(int id)
        {
            LoadDB();
            editProduct = productDB.lookforID(id);
        }
        public IActionResult OnPost()
        {

            LoadDB();
            productDB.Edit(editProduct.id, editProduct);
            SaveDB();
            return RedirectToPage("List");
        }
    }
}

PS4/PS4/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PS4.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PS4/PS4/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace PS4.Pages
{
    public class IndexModel : PageModel
    {
        public IActionResult OnPost()
        {
            return RedirectToPage("List", "");
        }
    }
}

PS4/PS4/Pages/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PS4.Models;

namespace PS4
{
    public class ListModel : MyPageModel
    {
        public List<Product> productList;
        public void OnGet()
        {
            LoadDB();
            productList = productDB.List();
            SaveDB();
        }
    }
}

PS4/PS4/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PS4.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PS4/PS4/Pages/ShopCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PS4.DAL;
using PS4.Models;

namespace PS4.Pages
{
    public class ShopCartModel : MyPageModel
    {

        public void OnGet()
        {
            LoadDB();
            shopcartDB.Clear();
            for (int i = 1; ; i++)
            {
                string add = Request.Cookies[i.ToString()];
                if (add == null) break;
                else shopcartDB.AddToCart(productDB.lookforID(int.Parse(add)));
            }
            SaveDB();
        }
        public IActionResult OnPostDelete()
        {
            shopcartDB.Clear();
            for (int i = 1; ; i++)
            {
                string add = Request.Cookies[i.ToString()];
                if (add == null) break;
                else Response.Cookies.Delete(add);
            }
            return Page();
        }
    }
}

PS4/PS4/Pages/Create.cshtml
@page
@model PS4.CreateModel
@{
    ViewData["Title"] = "Nowy produkt";
}
<h2>Nowy produkt</h2>
<br />
<br />
<div class="container">
    <form class="form-horizontal" method="post">
        <div class="form-group">
            <label asp-for="newProduct.name" class="control-label col-sm2"></label>
            <div class="col-sm-6">
                <input asp-for="newProduct.name" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label asp-for="newProduct.price" class="control-label col-sm2"></label>
            <div class="col-sm-6">
                <input asp-for="newProduct.price" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn btn-primary">Zatwierdź</button>
            </div>
        </div>
    </form>
</div>

PS4/PS4/Pages/Delete.cshtml
@page
@model PS4.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

PS4/PS4/Pages/Details.cshtml
@page
@model PS4.Pages.DetailsModel
@{
    ViewData["Title"] = "Details";
}
<h1>Szczegóły</h1>
<div class="container">
    <br />
    Informacje na temat produktu. Każdy sprzedawany towar jest najwyżej jakości!
    <br />
    Nazwa: @Model.product.name <b> *odznaczony medalem jakości produktu* </b>

    <br />
    Cena: @Model.product.price złotych polskich

    <br />
    <br />

    <form asp-page-handler="Add" method="post">
        <button class="btn btn-primary btn-large">Zakup wybrany produkt</button>
        <input type="hidden" name="id" value="@Model.product.id" />
    </form>
</div>

PS4/PS4/Pages/Edit.cshtml
@page
@model PS4.Pages.EditModel
@{
    ViewData["Title"] = "Edytuj";
}

<h2>Edytuj</h2>
<br />
<br />
<div class="container">
    <form class="form-horizontal" method="post">
        <div class="form-group">
            @Html.Hidden("editProduct.id", Model.editProduct.id)
            <label asp-for="editProduct.name" class="control-label col-sm2"></label>
            <div class="col-sm-6">
                <input asp-for="editProduct.name" class="form-control" value="@Model.editProduct.name">
                <span asp-validation-for="editProduct.name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="editProduct.price" class="control-label col-sm2"></label>
            <div class="col-sm-6">
                <input asp-for="editProduct.price" class="form-control" value="@Model.editProduct.price">
                <span asp-validation-for="editProduct.price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn btn-primary">Zatwierdź</button>
            </div>
        </div>
    </form>
</div>

PS4/PS4/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Strona startowa";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <title>Strona główna</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body style="background-color: antiquewhite; color: black">
    <center>

        <h4 class="display-4"> Witaj w nowym sklepie osiedlowym!</h4>
        <br />
        <form method="post">
            <input type="submit" value="Rozpocznij zakupy" />
        </form>
    </center>
</body>
</html>

PS4/PS4/Pages/List.cshtml
@page
@model ListModel
@{
    ViewData["Title"] = "Lista produktów";
}
<h2>Lista produktów</h2>
<div class="row col-sm-12">
    <a asp-page="Create" class="btn btn-primary btn-large">Dodaj</a>
    <a asp-page="ShopCart" class="btn btn-primary btn-large">Koszyk</a>
</div>
<br />
<br />
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => Model.productList[0].id)</th>
            <th scope="col">@Html.DisplayNameFor(model => Model.productList[0].name)</th>
            <th scope="col">@Html.DisplayNameFor(model => Model.productList[0].price)</th>
            <th scope="col">Akcja</th>
    </thead>
    <tbody style="background-color: antiquewhite; color: black">
        @foreach (var p in Model.productList)
        {
            <tr>
                <th scope="row">@Html.DisplayFor(m => p.id)</th>
                <td>@Html.DisplayFor(m => p.name)</td>
                <td>@Html.DisplayFor(m => p.price)</td>
                <td>
                    <a asp-page="Details" asp-route-id=@p.id>Szczegóły</a> |
                    <a asp-page="Edit" asp-route-id=@p.id>Edytuj</a> |
                    <a asp-page="Delete" asp-route-id=@p.id>Kasuj</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

PS4/PS4/Pages/ShopCart.cshtml
@page
@model PS4.Pages.ShopCartModel
@{
    ViewData["Title"] = "Koszyk";
}

<h1>Koszyk</h1>
<div class="container">
    @if (Model.shopcartDB.GetProductsList != null)
    {
        @foreach (var i in Model.shopcartDB.GetProductsList)
        {
    <div>
        @(i?.name ?? "Brak produktu w sklepie.")
    </div>
        }
    }

    <div class="row col-sm-12">
        <a asp-page="List" class="btn btn-primary btn-large">Powrót do Sklepu</a>
        <form asp-page-handler="Delete" method="post">
            <button class="btn btn-primary btn-large">Nowy Koszyk</button>
        </form>

    </div>
</div>